# Generated by Django 4.1 on 2022-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'В очереди'), (1, 'В работе'), (2, 'Завершено')], default=0, verbose_name='Статус'),
        ),
    ]
